apiVersion: jpe.prabhatsharma.in/v1alpha1
kind: AdmissionPolicy
metadata:
  name: simplepolicy
  namespace: default
spec:
  rules:
  - name: rule1
    resource: pod
    validationFailureAction: enforce
    rule: |
      validate(resource){
        if(resource.metadata.name == "simple1") {
          return true;
        }
        return false;
      }



