apiVersion: jpe.prabhatsharma.in/v1alpha1
kind: AdmissionPolicy
metadata:
  name: simplepolicy
  namespace: default
spec:
  rules:
  - name: rule1
    resource: pod
    validationFailureAction: enforce
    description: Any pods that have the name simple are really weird and we should prevent them from running. 
    message: Pod name should not be simple.
    rule: |
      function validate(resource){
        resource = JSON.parse(resource);
        if(resource.metadata.name != "simple") {
          return true;
        };
        return false;
      }



