apiVersion: v1
kind: ServiceAccount
metadata:
  name: jpe
  namespace: jpe

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jpe
  namespace: default
rules:
- apiGroups: ["jpe.prabhatsharma.in"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jpe
  namespace: default
subjects:
- kind: ServiceAccount
  name: jpe
  namespace: jpe
roleRef:
  kind: ClusterRole
  name: jpe
  apiGroup: rbac.authorization.k8s.io

