package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *AdmissionPolicy) DeepCopyInto(out *AdmissionPolicy) {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.Spec = AdmissionPolicySpec{
		Rules: in.Spec.Rules,
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionPolicy.
func (in *AdmissionPolicy) DeepCopy() *AdmissionPolicy {
	if in == nil {
		return nil
	}
	out := new(AdmissionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of an object
func (in *AdmissionPolicy) DeepCopyObject() runtime.Object {
	out := AdmissionPolicy{}
	in.DeepCopyInto(&out)

	return &out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionPolicyList) DeepCopyInto(out *AdmissionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdmissionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionPolicyList.
func (in *AdmissionPolicyList) DeepCopy() *AdmissionPolicyList {
	if in == nil {
		return nil
	}
	out := new(AdmissionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of an object
func (in *AdmissionPolicyList) DeepCopyObject() runtime.Object {
	out := AdmissionPolicyList{}
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta

	if in.Items != nil {
		out.Items = make([]AdmissionPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}

	return &out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionPolicySpec) DeepCopyInto(out *AdmissionPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionPolicySpec.
func (in *AdmissionPolicySpec) DeepCopy() *AdmissionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AdmissionPolicySpec)
	in.DeepCopyInto(out)
	return out
}



